### ISSUE TITLE
Inconsistent results from bowtie and methylpy

### ISSUE THREAD

**Issue by coralzhang** [yupenghe/yupenghe.github.io#2]
Hi, I have been using the methylpy for my WGBS data analysis. 
I am not sure how to explain the inconsistency between the log from bowtie2 and methylpy. 
Here is the bowtie2 output directed by methylpy. 

> 154046785 reads; of these:aligned >1 times
  154046785 (100.00%) were paired; of these:
    49652641 (32.23%) aligned concordantly 0 times
    40781750 (26.47%) aligned concordantly exactly 1 time
    63612394 (41.29%) aligned concordantly >1 times
    ----
    49652641 pairs aligned concordantly 0 times; of these:
      787081 (1.59%) aligned discordantly 1 time
    ----
    48865560 pairs aligned 0 times concordantly or discordantly; of these:
      97731120 mates make up the pairs; of these:
        76102423 (77.87%) aligned 0 times
        7975839 (8.16%) aligned exactly 1 time
        13652858 (13.97%) aligned >1 times
75.30% overall alignment rate
154046785 reads; of these:
  154046785 (100.00%) were paired; of these:
    49891139 (32.39%) aligned concordantly 0 times
    40662192 (26.40%) aligned concordantly exactly 1 time
    63493454 (41.22%) aligned concordantly >1 times
    ----
    49891139 pairs aligned concordantly 0 times; of these:
      815159 (1.63%) aligned discordantly 1 time
    ----
    49075980 pairs aligned 0 times concordantly or discordantly; of these:
      98151960 mates make up the pairs; of these:
        76516998 (77.96%) aligned 0 times
        8020870 (8.17%) aligned exactly 1 time
        13614092 (13.87%) aligned >1 times
75.16% overall alignment rate

Here is the summary from methylpy. 

> There are 154046785 total input read pairs
Fri Nov 10 21:31:50 2017
There are 129781122 uniquely mapping read pairs, 84.2478614533 percent remaining
Fri Nov 10 21:31:50 2017

What exactly is the percentage of uniquely mapped read pairs?
Maybe there is an explanation somewhere else, but I just could not figure out at the moment. Anysuggestions can be helpful. THanks!

**Comment by yupenghe** [comment]
129781122 is the correct number and if you did not do clonal read removal, that should be the number of reads in the final bam file. 

The confusion comes from the fact that each read (pair) actually is mapped twice to forward reference (generated by converting Cs to Ts) and reverse reference (generated by converting Gs to As). The bowtie mapping rates you saw are the mapping rates for these two alignments. Then, methylpy will merge the alignments by throwing out reads that can be mapped to both references (which are multi-map and we cannot confidently identity their actually original locations in the genome). Reads that pass this merging step are considered as uniquely mapped and the number 129781122 refers to these reads.

**Comment by coralzhang** [comment]
Thank you very much! That is understandable.
